### ISSUE TITLE
PyQt version missing from documentation

### ISSUE THREAD

**Issue by andreasharbo** [arnaudframmery/qt-tile-layout#1]
Hi

I recently tried tile layout and it works nicely out of the box. I am having some rendering and garbage collection issues, though, So i was wondering what version of PyQt you are using, since that might be what is causing my problems.

I am using PyQt 5.12.2

I will later create few specific issues with the problems i am experiencing, and possibly a pull request.

Cheers!

**Comment by arnaudframmery** [comment]
Hello,

I am using PyQt **5.15.3** in this project and also **5.15.2** in another one where I am using this tile layout.
So yes, there is a chance that your issue comes from the version gap between you and me, I will update this repo soon with a requirements file to avoid any version issue in the futur.

Moreover, if you are using the tile layout in non static mode, there is a high chance that you will experience some rendering issues. I have found out some tricks to correct that so I will also add it in the test file in the futur.

Anyways thank you for your message and feel free to open other issues or pull request.

Cheers

**Comment by arnaudframmery** [comment]
Okay I have tried on 5.12.3 and there are some terrible rendering issues, upgrade to 5.15.* should resolve a big part of them I think

**Comment by andreasharbo** [comment]
Unfortunately i cannot upgrade due to other dependencies. I have solved the problem though and i will submit a PR in near future :)

**Comment by arnaudframmery** [comment]
Since your PR has resolved issues with PyQt 5.12.2 I will soon update requirements and pypi package with a new minimum version after some tests with old PyQt versions, after that I will close this issue :)
